name: Run Stocks Script

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
    contents: write

jobs:
  run-stocks-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r Financial/requirements.txt

      - name: Run stocks.py
        run: python Financial/stocks.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated changes by stocks.py script" || echo "No changes to commit"
          git push origin main
